package Client;
import java.io.IOException;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import Page_Objects.ClientSignUp;
import Resource_Properties.Base_File;

public class ClientAccountSignUp extends Base_File
{

	@BeforeMethod
	public void initialize() throws IOException
	{
		driver = initializeBrowser();
		driver.get(pro.getProperty("url"));
	}
	
	@Test(priority=1)
	public void SignUp_AccountCreationWith_NoPackage()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Brie");
		a.LastName().sendKeys("Johnsson");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4526534563");
		a.DOB().sendKeys("09061994");
		a.selectGender().click();
		a.Female().click();
		a.Address1().sendKeys("Highland Street 120");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Alex");
		a.eLastName().sendKeys("Johnsson");
		a.eEmail().sendKeys("alex.johnsson@gmail.com");
		a.ePhoneNo().sendKeys("4625676548");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.skipPurchasePackageLater().click();
		a.skipPackage_Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Brie Johnsson");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Brie Johnsson");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Brie");
		Assert.assertEquals(a.confirmLastName().getText(), "Johnsson");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4526534563");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 120");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Alex");
		Assert.assertEquals(a.confirmELastName().getText(), "Johnsson");
		Assert.assertEquals(a.confirmEEmail().getText(), "alex.johnsson@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4625676548");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");
		a.Confirm().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.dontHaveAPackageMessage().getText(), "You don't have a package on file for this session.\n"+"Would you like to purchase a new package?");
				
	}
	
	@Test(priority=2)
	public void SignUp_AccountCreationWith_FreeTrailPack()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Jennifer");
		a.LastName().sendKeys("Lawrence");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4624565674");
		a.DOB().sendKeys("03091994");
		a.selectGender().click();
		a.Female().click();
		a.Address1().sendKeys("Highland Street 140");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Anne");
		a.eLastName().sendKeys("Lawrence");
		a.eEmail().sendKeys("anne.lawrence@gmail.com");
		a.ePhoneNo().sendKeys("4626456842");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.zero$classPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Jennifer Lawrence");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Jennifer Lawrence");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Jennifer");
		Assert.assertEquals(a.confirmLastName().getText(), "Lawrence");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4624565674");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 140");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Anne");
		Assert.assertEquals(a.confirmELastName().getText(), "Lawrence");
		Assert.assertEquals(a.confirmEEmail().getText(), "anne.lawrence@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4626456842");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");
		a.Confirm().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));	
	}
	
	@Test(priority=3)
	public void SignUp_AccountCreationWith_PurchaseClassPack() 
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Alexandra");
		a.LastName().sendKeys("Daddario");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4825434121");
		a.Address1().sendKeys("Highland Street 120");
		a.City().sendKeys("Atlanta");
		a.DOB().sendKeys("09091995");
		a.selectGender().click();
		a.Female().click();
		a.Zip().sendKeys("30303");
		a.State().click();
		a.Georgia().click();
		a.eFirstName().sendKeys("Nina");
		a.eLastName().sendKeys("Daddario");
		a.eEmail().sendKeys("nina.daddario@gmail.com");
		a.ePhoneNo().sendKeys("4853453412");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.$classPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Alexandra Daddario");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Alexandra Daddario");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Alexandra");
		Assert.assertEquals(a.confirmLastName().getText(), "Daddario");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4825434121");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 120");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Nina");
		Assert.assertEquals(a.confirmELastName().getText(), "Daddario");
		Assert.assertEquals(a.confirmEEmail().getText(), "nina.daddario@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4853453412");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");	
		Assert.assertEquals(a.actualGrandTotalName().getText(), "Grand Total");
		Assert.assertEquals(a.actualGrandTotalAmount().getText(), "$1.00");
		a.promoCode().sendKeys("yog247");
		a.promoCodeApply().click();
		Assert.assertEquals(a.promoCodeAppliedMessage().getText(), "Your promo code has been applied successfully!");
		Assert.assertEquals(a.promoCodeName().getText(), "Promo-(yog247)");
		Assert.assertEquals(a.promoCodeAmount().getText(), "-$0.50");
		Assert.assertEquals(a.grandTotalNameAfterDiscount().getText(), "Grand Total");
		Assert.assertEquals(a.grandTotalAmountAfterDiscount().getText(), "$0.50");
		a.sameAsClientDetails().click();
		Assert.assertEquals(a.cardHolderFirstName().getAttribute("value"), "Alexandra");
		Assert.assertEquals(a.cardHolderLastName().getAttribute("value"), "Daddario");
		Assert.assertEquals(a.cardHolderEmail().getAttribute("value"), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.cardHolderAddress().getAttribute("value"), "Highland Street 120");
		Assert.assertEquals(a.cardHolderCity().getAttribute("value"), "Atlanta");
		Assert.assertEquals(a.cardHolderZip().getAttribute("value"), "30303");
		a.EnterCreditCardNo().sendKeys("4242424242424242");
		a.EnterExpiryDate().sendKeys("0224");
		a.EnterCVV().sendKeys("4391");
		a.Confirm_pay().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login_afterPay().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));
	}
	
	@Test(priority=4)
	public void SignUp_AccountCreationWith_PurchaseMemPack()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Elizabeth");
		a.LastName().sendKeys("Olsen");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4805434121");
		a.DOB().sendKeys("09091995");
		a.selectGender().click();
		a.Female().click();
		a.Address1().sendKeys("Highland Street 150");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Natalie");
		a.eLastName().sendKeys("Olsen");
		a.eEmail().sendKeys("natalie.olsen@gmail.com");
		a.ePhoneNo().sendKeys("4853453412");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.xSessionsMemPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Elizabeth Olsen");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Elizabeth Olsen");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Elizabeth");
		Assert.assertEquals(a.confirmLastName().getText(), "Olsen");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4805434121");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 150");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Natalie");
		Assert.assertEquals(a.confirmELastName().getText(), "Olsen");
		Assert.assertEquals(a.confirmEEmail().getText(), "natalie.olsen@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4853453412");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");
		Assert.assertEquals(a.actualGrandTotalName().getText(), "Grand Total");
		Assert.assertEquals(a.actualGrandTotalAmount().getText(), "$1.00");
		a.promoCode().sendKeys("mempack23");
		a.promoCodeApply().click();
		Assert.assertEquals(a.promoCodeAppliedMessage().getText(), "Your promo code has been applied successfully!");
		Assert.assertEquals(a.promoCodeName().getText(), "Promo-(mempack23)");
		Assert.assertEquals(a.promoCodeAmount().getText(), "-$0.50");
		Assert.assertEquals(a.grandTotalNameAfterDiscount().getText(), "Grand Total");
		Assert.assertEquals(a.grandTotalAmountAfterDiscount().getText(), "$0.50");		
		a.sameAsClientDetails().click();
		Assert.assertEquals(a.cardHolderFirstName().getAttribute("value"), "Elizabeth");
		Assert.assertEquals(a.cardHolderLastName().getAttribute("value"), "Olsen");
		Assert.assertEquals(a.cardHolderEmail().getAttribute("value"), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.cardHolderAddress().getAttribute("value"), "Highland Street 150");
		Assert.assertEquals(a.cardHolderCity().getAttribute("value"), "Atlanta");
		Assert.assertEquals(a.cardHolderZip().getAttribute("value"), "30303");
		a.EnterCreditCardNo().sendKeys("4242424242424242");
		a.EnterExpiryDate().sendKeys("0224");
		a.EnterCVV().sendKeys("4391");
		a.agreeToChargeMonthlyCheckbox().click();
		a.Confirm_pay().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login_afterPay().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));
	}
	
	@Test(priority=5)
	public void SignUp_AccountCreationWith_PurchaseUnlimitedMem()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Matthew");
		a.LastName().sendKeys("McConaughey");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4567765420");
		a.DOB().sendKeys("09301994");
		a.selectGender().click();
		a.Male().click();
		a.Address1().sendKeys("Highland Street 140");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Alex");
		a.eLastName().sendKeys("McConaughey");
		a.eEmail().sendKeys("alex.mcconaughey@gmail.com");
		a.ePhoneNo().sendKeys("4567876545");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.unlimitedMemPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Matthew McConaughey");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Matthew McConaughey");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Matthew");
		Assert.assertEquals(a.confirmLastName().getText(), "McConaughey");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4567765420");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 140");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Alex");
		Assert.assertEquals(a.confirmELastName().getText(), "McConaughey");
		Assert.assertEquals(a.confirmEEmail().getText(), "alex.mcconaughey@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4567876545");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");	
		Assert.assertEquals(a.actualGrandTotalName().getText(), "Grand Total");
		Assert.assertEquals(a.actualGrandTotalAmount().getText(), "$1.00");
		a.promoCode().sendKeys("mempack23");
		a.promoCodeApply().click();
		Assert.assertEquals(a.promoCodeAppliedMessage().getText(), "Your promo code has been applied successfully!");
		Assert.assertEquals(a.promoCodeName().getText(), "Promo-(mempack23)");
		Assert.assertEquals(a.promoCodeAmount().getText(), "-$0.50");
		Assert.assertEquals(a.grandTotalNameAfterDiscount().getText(), "Grand Total");
		Assert.assertEquals(a.grandTotalAmountAfterDiscount().getText(), "$0.50");	
		a.sameAsClientDetails().click();
		Assert.assertEquals(a.cardHolderFirstName().getAttribute("value"), "Matthew");
		Assert.assertEquals(a.cardHolderLastName().getAttribute("value"), "McConaughey");
		Assert.assertEquals(a.cardHolderEmail().getAttribute("value"), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.cardHolderAddress().getAttribute("value"), "Highland Street 140");
		Assert.assertEquals(a.cardHolderCity().getAttribute("value"), "Atlanta");
		Assert.assertEquals(a.cardHolderZip().getAttribute("value"), "30303");
		a.EnterCreditCardNo().sendKeys("4242424242424242");
		a.EnterExpiryDate().sendKeys("0224");
		a.EnterCVV().sendKeys("1204");
		a.agreeToChargeMonthlyCheckbox().click();
		a.Confirm_pay().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login_afterPay().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));	
	}
	
	@Test(priority=6)
	public void SignUp_AccountCreationWith_FreeFirstMonthMemPack()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Julianne");
		a.LastName().sendKeys("Moore");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4565434567");
		a.DOB().sendKeys("09301994");
		a.selectGender().click();
		a.GenderVariant().click();
		a.Address1().sendKeys("Highland Street 120");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Odette");
		a.eLastName().sendKeys("Moore");
		a.eEmail().sendKeys("odette.moore@gmail.com");
		a.ePhoneNo().sendKeys("4567645674");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.freeFirstMonthMemPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Julianne Moore");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Julianne Moore");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Julianne");
		Assert.assertEquals(a.confirmLastName().getText(), "Moore");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4565434567");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 120");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Odette");
		Assert.assertEquals(a.confirmELastName().getText(), "Moore");
		Assert.assertEquals(a.confirmEEmail().getText(), "odette.moore@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4567645674");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");
		Assert.assertEquals(a.actualGrandTotalName().getText(), "Grand Total");
		Assert.assertEquals(a.actualGrandTotalAmount().getText(), "$0.00");
		a.sameAsClientDetails().click();
		Assert.assertEquals(a.cardHolderFirstName().getAttribute("value"), "Julianne");
		Assert.assertEquals(a.cardHolderLastName().getAttribute("value"), "Moore");
		Assert.assertEquals(a.cardHolderEmail().getAttribute("value"), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.cardHolderAddress().getAttribute("value"), "Highland Street 120");
		Assert.assertEquals(a.cardHolderCity().getAttribute("value"), "Atlanta");
		Assert.assertEquals(a.cardHolderZip().getAttribute("value"), "30303");
		a.EnterCreditCardNo().sendKeys("4242424242424242");
		a.EnterExpiryDate().sendKeys("0224");
		a.EnterCVV().sendKeys("1041");
		a.agreeToChargeMonthlyCheckbox().click();
		a.Confirm_pay().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(), "Congratulations! Your account has been created.");	
		a.Login_afterPay().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));
	}
	
	@Test(priority=7)
	public void SignUp_AccountCreationWith_PurchaseClassAndMemPack()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Elle");
		a.LastName().sendKeys("Fanning");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4825434121");
		a.DOB().sendKeys("09091995");
		a.selectGender().click();
		a.PreferNotDisclose().click();
		a.Address1().sendKeys("Highland Street 125");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Emilia");
		a.eLastName().sendKeys("Fanning");
		a.eEmail().sendKeys("emilia.fanning@gmail.com");
		a.ePhoneNo().sendKeys("4253453412");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.$classPack().click();
		a.xSessionsMemPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Elle Fanning");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Elle Fanning");
		a.SaveAndContinue4().click();	
		Assert.assertEquals(a.confirmFirstName().getText(), "Elle");
		Assert.assertEquals(a.confirmLastName().getText(), "Fanning");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4825434121");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 125");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Emilia");
		Assert.assertEquals(a.confirmELastName().getText(), "Fanning");
		Assert.assertEquals(a.confirmEEmail().getText(), "emilia.fanning@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4253453412");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");
		Assert.assertEquals(a.actualGrandTotalName_ClassAndMem().getText(), "Grand Total");
		Assert.assertEquals(a.actualGrandTotalAmount_ClassAndMem().getText(), "$2.00");
		a.promoCode().sendKeys("mempack23");
		a.promoCodeApply().click();
		Assert.assertEquals(a.promoCodeAppliedMessage().getText(), "Your promo code has been applied successfully!");
		Assert.assertEquals(a.promoCodeName_ClassAndMem().getText(), "Promo-(mempack23)");
		Assert.assertEquals(a.promoCodeAmount_ClassAndMem().getText(), "-$0.50");
		Assert.assertEquals(a.grandTotalName_ClassAndMem_AfterDiscount().getText(), "Grand Total");
		Assert.assertEquals(a.grandTotalAmount_ClassAndMem_AfterDiscount().getText(), "$1.50");
		a.sameAsClientDetails().click();
		Assert.assertEquals(a.cardHolderFirstName().getAttribute("value"), "Elle");
		Assert.assertEquals(a.cardHolderLastName().getAttribute("value"), "Fanning");
		Assert.assertEquals(a.cardHolderEmail().getAttribute("value"), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.cardHolderAddress().getAttribute("value"), "Highland Street 125");
		Assert.assertEquals(a.cardHolderCity().getAttribute("value"), "Atlanta");
		Assert.assertEquals(a.cardHolderZip().getAttribute("value"), "30303");
		a.EnterCreditCardNo().sendKeys("4242424242424242");
		a.EnterExpiryDate().sendKeys("0224");
		a.EnterCVV().sendKeys("4391");
		a.agreeToChargeMonthlyCheckbox().click();
		a.Confirm_pay().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login_afterPay().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+" + randomInt + "@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));	
	}	
	
	@Test(priority=8)
	public void SignUp_AccountCreationWith_PurchaseClassAndMemPack_ClassPackPromoCode()
	{
		ClientSignUp a = new ClientSignUp(driver);
		a.signUpLink().click();
		a.FirstName().sendKeys("Isabella");
		a.LastName().sendKeys("Fanning");
		String randomInt = a.Email();
		a.PhoneNo().sendKeys("4825434121");
		a.DOB().sendKeys("09091995");
		a.selectGender().click();
		a.PreferNotDisclose().click();
		a.Address1().sendKeys("Highland Street 120");
		a.City().sendKeys("Atlanta");
		a.State().click();
		a.Georgia().click();
		a.Zip().sendKeys("30303");
		a.eFirstName().sendKeys("Emma");
		a.eLastName().sendKeys("Fanning");
		a.eEmail().sendKeys("emma.fanning@gmail.com");
		a.ePhoneNo().sendKeys("4253453412");
		a.eRelationship().sendKeys("Sister");
		a.Password().sendKeys("Password@3");
		a.ConfirmPassword().sendKeys("Password@3");
		a.SaveAndContinue1().click();
		a.$classPack().click();
		a.xSessionsMemPack().click();
		a.SaveAndContinue2().click();
		a.Term1Checkbox().click();
		a.Term2Checkbox().click();
		a.DefaultCheckbox().click();
		a.TypeFullName().sendKeys("Isabella Fanning");
		a.SaveAndContinue3().click();
		a.PoliciesTerm1().click();
		a.PoliciesTerm2().click();
		a.PoliciesDefaultCheckbox().click();
		a.PoliciesTypeFullName().sendKeys("Isabella Fanning");
		a.SaveAndContinue4().click();
		Assert.assertEquals(a.confirmFirstName().getText(), "Isabella");
		Assert.assertEquals(a.confirmLastName().getText(), "Fanning");
		Assert.assertEquals(a.confirmEmail().getText(), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.confirmPhoneNo().getText(), "4825434121");
		Assert.assertEquals(a.confirmAddress().getText(), "Highland Street 120");
		Assert.assertEquals(a.confirmEFirstName().getText(), "Emma");
		Assert.assertEquals(a.confirmELastName().getText(), "Fanning");
		Assert.assertEquals(a.confirmEEmail().getText(), "emma.fanning@gmail.com");
		Assert.assertEquals(a.confirmEPhoneNo().getText(), "4253453412");
		Assert.assertEquals(a.confirmERelationship().getText(), "Sister");
		Assert.assertEquals(a.actualGrandTotalName_ClassAndMem().getText(), "Grand Total");
		Assert.assertEquals(a.actualGrandTotalAmount_ClassAndMem().getText(), "$2.00");
		a.promoCode().sendKeys("yog247");
		a.promoCodeApply().click();
		Assert.assertEquals(a.promoCodeAppliedMessage().getText(), "Your promo code has been applied successfully!");
		Assert.assertEquals(a.promoCodeName_ClassAndMem().getText(), "Promo-(yog247)");
		Assert.assertEquals(a.promoCodeAmount_ClassAndMem().getText(), "-$0.50");
		Assert.assertEquals(a.grandTotalName_ClassAndMem_AfterDiscount().getText(), "Grand Total");
		Assert.assertEquals(a.grandTotalAmount_ClassAndMem_AfterDiscount().getText(), "$1.50");
		a.sameAsClientDetails().click();
		Assert.assertEquals(a.cardHolderFirstName().getAttribute("value"), "Isabella");
		Assert.assertEquals(a.cardHolderLastName().getAttribute("value"), "Fanning");
		Assert.assertEquals(a.cardHolderEmail().getAttribute("value"), "jyoti.kharatmol+"+randomInt+"@azularc.com");
		Assert.assertEquals(a.cardHolderAddress().getAttribute("value"), "Highland Street 120");
		Assert.assertEquals(a.cardHolderCity().getAttribute("value"), "Atlanta");
		Assert.assertEquals(a.cardHolderZip().getAttribute("value"), "30303");	
		a.EnterCreditCardNo().sendKeys("4242424242424242");
		a.EnterExpiryDate().sendKeys("0224");
		a.EnterCVV().sendKeys("4391");
		a.agreeToChargeMonthlyCheckbox().click();
		a.Confirm_pay().click();
		Assert.assertEquals(a.AccountCreationSuccessfulMessage().getText(),"Congratulations! Your account has been created.");
		a.Login_afterPay().click();
		a.clientUsername().sendKeys("jyoti.kharatmol+"+randomInt+"@azularc.com");
		a.clientPassword().sendKeys("Password@3");
		a.clientLogin().click();
		a.SessionOnCalendar().click();
		a.sessionSignUp().click();
		Assert.assertEquals(a.sessionSignedUpMessage().getText(), "You have been registered for this session!");
		Assert.assertTrue(a.cancelSession().isDisplayed());
		Assert.assertTrue(a.sessionModalShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.sessionOnCalendarShownWith_GreenCheckMark().isDisplayed());
		Assert.assertTrue(a.packageStatus().getText().contains("1/"));	
	}	
	
	@AfterMethod
	public void tearDown()
	{
		driver.close();
	}

	
}
